Select ITEM_ID,
'ref' AS "ITEM_ID_ns",
'RECORD_ID' AS "ITEM_ID_name",
Attribute_142,
'ref' AS "Attribute_142_ns",
'RequestId' AS "Attribute_142_name",
Attribute_136,
'ref' AS "Attribute_136_ns",
'ServiceMax_Standard_PSID' AS "Attribute_136_name",
Attribute_140,
'ref' AS "Attribute_140_ns",
'PackageLicenseId' AS "Attribute_140_name",
Attribute_125,
'ref' AS "Attribute_125_ns",
'Environment' AS "Attribute_125_name",
Attribute_21,
'ref' AS "Attribute_21_ns",
'Oracle_Location_Number' AS "Attribute_21_name",
Attribute_22,
'ref' AS "Attribute_22_ns",
'Oracle_SubInventory' AS "Attribute_22_name",
Attribute_138,
'ref' AS "Attribute_138_ns",
'Product_Pricebook_PSID' AS "Attribute_138_name",
Attribute_24,
'user' AS "Attribute_24_ns",
'FirstName' AS "Attribute_24_name",
Attribute_25,
'user' AS "Attribute_25_ns",
'LastName' AS "Attribute_25_name",
Attribute_26,
'user' AS "Attribute_26_ns",
'SSO__c' AS "Attribute_26_name",
Attribute_27,
'user' AS "Attribute_27_ns",
'FederationIdentifier' AS "Attribute_27_name",
Attribute_28,
'user' AS "Attribute_28_ns",
'ProfileId' AS "Attribute_28_name",
Attribute_29,
'user' AS "Attribute_29_ns",
'Email' AS "Attribute_29_name",
Attribute_30,
'user' AS "Attribute_30_ns",
'Global_Region__c' AS "Attribute_30_name",
Attribute_31,
'user' AS "Attribute_31_ns",
'Global_Sub_Region__c' AS "Attribute_31_name",
Attribute_32,
'user' AS "Attribute_32_ns",
'Territory__c' AS "Attribute_32_name",
Attribute_34,
'user' AS "Attribute_34_ns",
'TimeZoneSidKey' AS "Attribute_34_name",
Attribute_35,
'user' AS "Attribute_35_ns",
'CurrencyIsoCode' AS "Attribute_35_name",
Attribute_36,
'user' AS "Attribute_36_ns",
'ManagerId' AS "Attribute_36_name",
Attribute_37,
'user' AS "Attribute_37_ns",
'Alias' AS "Attribute_37_name",
Attribute_38,
'user' AS "Attribute_38_ns",
'CommunityNickname' AS "Attribute_38_name",
Attribute_39,
'user' AS "Attribute_39_ns",
'Username' AS "Attribute_39_name",
Attribute_40,
'user' AS "Attribute_40_ns",
'IsActive' AS "Attribute_40_name",
Attribute_41,
'user' AS "Attribute_41_ns",
'UserPreferencesActivityRemindersPopup' AS "Attribute_41_name",
Attribute_42,
'user' AS "Attribute_42_ns",
'ReceivesAdminInfoEmails' AS "Attribute_42_name",
Attribute_43,
'user' AS "Attribute_43_ns",
'ForecastEnabled' AS "Attribute_43_name",
Attribute_44,
'user' AS "Attribute_44_ns",
'UserPermissionsMobileUser' AS "Attribute_44_name",
Attribute_45,
'user' AS "Attribute_45_ns",
'UserPreferencesApexPagesDeveloperMode' AS "Attribute_45_name",
Attribute_46,
'user' AS "Attribute_46_ns",
'UserPermissionsCallCenterAutoLogin' AS "Attribute_46_name",
Attribute_47,
'user' AS "Attribute_47_ns",
'EmailPreferencesAutoBcc' AS "Attribute_47_name",
Attribute_48,
'user' AS "Attribute_48_ns",
'EmailPreferencesAutoBccStayInTouch' AS "Attribute_48_name",
Attribute_49,
'user' AS "Attribute_49_ns",
'UserPermissionsAvantgoUser' AS "Attribute_49_name",
Attribute_50,
'user' AS "Attribute_50_ns",
'Bypass_Custom_Validation__c' AS "Attribute_50_name",
Attribute_51,
'user' AS "Attribute_51_ns",
'UserPermissionsChatterAnswersUser' AS "Attribute_51_name",
Attribute_52,
'user' AS "Attribute_52_ns",
'UserPreferencesDisableAllFeedsEmail' AS "Attribute_52_name",
Attribute_53,
'user' AS "Attribute_53_ns",
'UserPreferencesDisableBookmarkEmail' AS "Attribute_53_name",
Attribute_54,
'user' AS "Attribute_54_ns",
'UserPreferencesDisableChangeCommentEmail' AS "Attribute_54_name",
Attribute_55,
'user' AS "Attribute_55_ns",
'UserPreferencesDisableEndorsementEmail' AS "Attribute_55_name",
Attribute_56,
'user' AS "Attribute_56_ns",
'UserPreferencesDisableFileShareNotificationsForApi' AS "Attribute_56_name",
Attribute_57,
'user' AS "Attribute_57_ns",
'UserPreferencesDisableFollowersEmail' AS "Attribute_57_name",
Attribute_58,
'user' AS "Attribute_58_ns",
'UserPreferencesDisableLaterCommentEmail' AS "Attribute_58_name",
Attribute_59,
'user' AS "Attribute_59_ns",
'UserPreferencesDisableLikeEmail' AS "Attribute_59_name",
Attribute_60,
'user' AS "Attribute_60_ns",
'UserPreferencesDisableMentionsPostEmail' AS "Attribute_60_name",
Attribute_61,
'user' AS "Attribute_61_ns",
'UserPreferencesDisableMessageEmail' AS "Attribute_61_name",
Attribute_62,
'user' AS "Attribute_62_ns",
'UserPreferencesDisableProfilePostEmail' AS "Attribute_62_name",
Attribute_63,
'user' AS "Attribute_63_ns",
'UserPreferencesDisableSharePostEmail' AS "Attribute_63_name",
Attribute_64,
'user' AS "Attribute_64_ns",
'UserPreferencesDisCommentAfterLikeEmail' AS "Attribute_64_name",
Attribute_65,
'user' AS "Attribute_65_ns",
'UserPreferencesDisMentionsCommentEmail' AS "Attribute_65_name",
Attribute_66,
'user' AS "Attribute_66_ns",
'UserPreferencesDisProfPostCommentEmail' AS "Attribute_66_name",
Attribute_67,
'user' AS "Attribute_67_ns",
'UserPreferencesEnableAutoSubForFeeds' AS "Attribute_67_name",
Attribute_68,
'user' AS "Attribute_68_ns",
'UserPreferencesEventRemindersCheckboxDefault' AS "Attribute_68_name",
Attribute_69,
'user' AS "Attribute_69_ns",
'UserPermissionsInteractionUser' AS "Attribute_69_name",
Attribute_70,
'user' AS "Attribute_70_ns",
'UserPreferencesHideChatterOnboardingSplash' AS "Attribute_70_name",
Attribute_71,
'user' AS "Attribute_71_ns",
'UserPreferencesHideCSNDesktopTask' AS "Attribute_71_name",
Attribute_72,
'user' AS "Attribute_72_ns",
'UserPreferencesHideCSNGetChatterMobileTask' AS "Attribute_72_name",
Attribute_73,
'user' AS "Attribute_73_ns",
'UserPreferencesHideS1BrowserUI' AS "Attribute_73_name",
Attribute_74,
'user' AS "Attribute_74_ns",
'UserPreferencesHideSecondChatterOnboardingSplash' AS "Attribute_74_name",
Attribute_75,
'user' AS "Attribute_75_ns",
'ReceivesInfoEmails' AS "Attribute_75_name",
Attribute_76,
'user' AS "Attribute_76_ns",
'SVMXC__Is_Super_Dispatcher__c' AS "Attribute_76_name",
Attribute_77,
'user' AS "Attribute_77_ns",
'UserPermissionsKnowledgeUser' AS "Attribute_77_name",
Attribute_78,
'user' AS "Attribute_78_ns",
'UserPreferencesLightningExperiencePreferred' AS "Attribute_78_name",
Attribute_79,
'user' AS "Attribute_79_ns",
'UserPermissionsMarketingUser' AS "Attribute_79_name",
Attribute_80,
'user' AS "Attribute_80_ns",
'UserPermissionsOfflineUser' AS "Attribute_80_name",
Attribute_81,
'user' AS "Attribute_81_ns",
'UserPreferencesReminderSoundOff' AS "Attribute_81_name",
Attribute_82,
'user' AS "Attribute_82_ns",
'UserPermissionsSFContentUser' AS "Attribute_82_name",
Attribute_83,
'user' AS "Attribute_83_ns",
'UserPermissionsSupportUser' AS "Attribute_83_name",
Attribute_84,
'user' AS "Attribute_84_ns",
'SVMXC__ServiceMax_User__c' AS "Attribute_84_name",
Attribute_85,
'user' AS "Attribute_85_ns",
'UserPreferencesShowCityToExternalUsers' AS "Attribute_85_name",
Attribute_86,
'user' AS "Attribute_86_ns",
'UserPreferencesShowCityToGuestUsers' AS "Attribute_86_name",
Attribute_87,
'user' AS "Attribute_87_ns",
'UserPreferencesShowCountryToExternalUsers' AS "Attribute_87_name",
Attribute_88,
'user' AS "Attribute_88_ns",
'UserPreferencesShowCountryToGuestUsers' AS "Attribute_88_name",
Attribute_89,
'user' AS "Attribute_89_ns",
'UserPreferencesShowEmailToExternalUsers' AS "Attribute_89_name",
Attribute_90,
'user' AS "Attribute_90_ns",
'UserPreferencesShowFaxToExternalUsers' AS "Attribute_90_name",
Attribute_91,
'user' AS "Attribute_91_ns",
'UserPreferencesShowManagerToExternalUsers' AS "Attribute_91_name",
Attribute_92,
'user' AS "Attribute_92_ns",
'UserPreferencesShowMobilePhoneToExternalUsers' AS "Attribute_92_name",
Attribute_93,
'user' AS "Attribute_93_ns",
'UserPreferencesShowPostalCodeToExternalUsers' AS "Attribute_93_name",
Attribute_94,
'user' AS "Attribute_94_ns",
'UserPreferencesShowPostalCodeToGuestUsers' AS "Attribute_94_name",
Attribute_95,
'user' AS "Attribute_95_ns",
'UserPreferencesShowProfilePicToGuestUsers' AS "Attribute_95_name",
Attribute_96,
'user' AS "Attribute_96_ns",
'UserPreferencesShowStateToExternalUsers' AS "Attribute_96_name",
Attribute_97,
'user' AS "Attribute_97_ns",
'UserPreferencesShowStateToGuestUsers' AS "Attribute_97_name",
Attribute_98,
'user' AS "Attribute_98_ns",
'UserPreferencesShowStreetAddressToExternalUsers' AS "Attribute_98_name",
Attribute_99,
'user' AS "Attribute_99_ns",
'UserPreferencesShowTitleToExternalUsers' AS "Attribute_99_name",
Attribute_100,
'user' AS "Attribute_100_ns",
'UserPreferencesShowTitleToGuestUsers' AS "Attribute_100_name",
Attribute_101,
'user' AS "Attribute_101_ns",
'UserPreferencesShowWorkPhoneToExternalUsers' AS "Attribute_101_name",
Attribute_102,
'user' AS "Attribute_102_ns",
'EmailPreferencesStayInTouchReminder' AS "Attribute_102_name",
Attribute_103,
'user' AS "Attribute_103_ns",
'UserPreferencesTaskRemindersCheckboxDefault' AS "Attribute_103_name",
Attribute_104,
'user' AS "Attribute_104_ns",
'UserPreferencesSortFeedByComment' AS "Attribute_104_name",
Attribute_105,
'user' AS "Attribute_105_ns",
'UserPreferencesCacheDiagnostics' AS "Attribute_105_name",
Attribute_106,
'user' AS "Attribute_106_ns",
'UserPreferencesHideBiggerPhotoCallout' AS "Attribute_106_name",
Attribute_107,
'user' AS "Attribute_107_ns",
'UserPreferencesHideEndUserOnboardingAssistantModal' AS "Attribute_107_name",
Attribute_108,
'user' AS "Attribute_108_ns",
'UserPreferencesHideLightningMigrationModal' AS "Attribute_108_name",
Attribute_109,
'user' AS "Attribute_109_ns",
'UserPreferencesHideSfxWelcomeMat' AS "Attribute_109_name",
Attribute_110,
'user' AS "Attribute_110_ns",
'UserPreferencesPathAssistantCollapsed' AS "Attribute_110_name",
Attribute_111,
'user' AS "Attribute_111_ns",
'UserPreferencesPreviewLightning' AS "Attribute_111_name",
Attribute_112,
'user' AS "Attribute_112_ns",
'UserPreferencesShowEmailToGuestUsers' AS "Attribute_112_name",
Attribute_113,
'user' AS "Attribute_113_ns",
'UserPreferencesShowFaxToGuestUsers' AS "Attribute_113_name",
Attribute_114,
'user' AS "Attribute_114_ns",
'UserPreferencesShowManagerToGuestUsers' AS "Attribute_114_name",
Attribute_115,
'user' AS "Attribute_115_ns",
'UserPreferencesShowMobilePhoneToGuestUsers' AS "Attribute_115_name",
Attribute_116,
'user' AS "Attribute_116_ns",
'UserPreferencesShowStreetAddressToGuestUsers' AS "Attribute_116_name",
Attribute_117,
'user' AS "Attribute_117_ns",
'UserPreferencesShowWorkPhoneToGuestUsers' AS "Attribute_117_name",
Attribute_118,
'user' AS "Attribute_118_ns",
'Business_P_L__c' AS "Attribute_118_name",
Attribute_119,
'user' AS "Attribute_119_ns",
'DigestFrequency' AS "Attribute_119_name",
Attribute_120,
'user' AS "Attribute_120_ns",
'DefaultGroupNotificationFrequency' AS "Attribute_120_name",
Attribute_121,
'user' AS "Attribute_121_ns",
'EmailEncodingKey' AS "Attribute_121_name",
Attribute_122,
'user' AS "Attribute_122_ns",
'LanguageLocaleKey' AS "Attribute_122_name",
Attribute_123,
'user' AS "Attribute_123_ns",
'LocaleSidKey' AS "Attribute_123_name",
Attribute_124,
'user' AS "Attribute_124_ns",
'UserRoleId' AS "Attribute_124_name",
Attribute_130,
'ref' AS "Attribute_130_ns",
'SF_User_Id' AS "Attribute_130_name",
io_user.geform_multi_option_value(Attribute_23) AS "ATTRIBUTE_23",
'ref' AS "Attribute_23_ns",
'ServiceTeam' AS "Attribute_23_name"
from GE_FORM_VALUES_211524
where Attribute_130 = ''
